jhjhjjh
Jrguerrero82/DISE-ODE-SITIOSWEB_OVI pull request #2
Opened 2020-04-12 02:17 UTC by dachalag

informacion

2020-04-12 03:57 UTC, Jrguerrero82 requested changes

2020-04-12 03:57 UTC, Jrguerrero82 commented on pagina1.html
> -                <h3> ELDISEÑO WEB EN COLOMBIA </h3>
elimine estas linea

2020-04-12 04:15 UTC, dachalag commented
listo

2020-04-16 01:14 UTC, Jrguerrero82 approved these changes

2020-04-23 15:50 UTC, closed without merging